### ISSUE TITLE
Error in data.frame(value, row.names = rn, check.names = FALSE, check.rows = FALSE) :    row.names should specify one of the variables

### ISSUE THREAD

**Issue by kretzlie** [benmarwick/JSTORr#3]
This showed up when I tried using the findassocs function (after creating mycorpus1). Possibly a problem in line 67 of the function?

**Comment by bounlu** [comment]
I get the same error.

**Comment by benmarwick** [comment]
Thanks, I'll take a look!

**Comment by benmarwick** [comment]
If you need something urgently to work with JSTOR data, try this pkg: https://github.com/tklebel/jstor
